---
version: 2
jobs:

  release:

    docker:
      - image: circleci/node:8

    steps:
      - checkout:
          path: ~/ansible-lint-rules

      - restore_cache:
          keys:
            - v1-dependencies-node-{{ checksum "package.json" }}

      - run:
          name: "Install node dependencies"
          command: |
            npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-node-{{ checksum "package.json" }}

      - run:
          name: "Release role"
          command: |
            ./node_modules/.bin/semantic-release
